apiVersion: apps/v1
kind: Deployment
metadata:
  name:  telemetry-pod
  labels:
    app:  telemetry-pod
spec:
  selector:
    matchLabels:
      app: telemetry-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: telemetry-pod
    spec:
      containers:
      - name: telemetry-pod
        image: sudarshan2026.azurecr.io/telemetry:z2
        
        ports:
        - containerPort: 8000
        
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ingestion-secret
              key: DATABASE_URL
