apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ingestion-pod
  labels:
    app:  ingestion-pod
spec:
  selector:
    matchLabels:
      app: ingestion-pod
  replicas: 2
  template:
    metadata:
      labels:
        app:  ingestion-pod
    spec:
      containers:
      - name:  ingestion-pod
        image: sudarshan2026.azurecr.io/ingestion:z2

        ports:
        - containerPort: 8000

        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ingestion-secret
              key: DATABASE_URL