apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasimulator
spec:
  selector:
    matchLabels:
      app: datasimulator-service
  template:
    metadata:
      labels:
        app: datasimulator-service
    spec:
      containers:
      - name: datasimulator-service
        image: sudarshan2026.azurecr.io/datasimulator:z1 
        env:
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: simulator-secret
              key: API_URL

        - name: INTERVAL_SECONDS
          valueFrom:
            secretKeyRef:
              name: simulator-secret
              key: INTERVAL_SECONDS


        ports:
        - containerPort: 8080

      
