apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
  labels:
    app: axion-ui

spec:
  selector:
    matchLabels:
      app: axion-ui

  replicas: 3

  template:
    metadata:
      labels:
        app: axion-ui

    spec:
      containers:
        - name: axion-ui
          image: sudarshan2026.azurecr.io/axionui:z4
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          
        